/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import model.Compras;
import model.EnlaceDescarga;
import model.Multimedia;

/**
 *
 * @author PC
 */
public class CompraHistorialCarrito extends javax.swing.JPanel {

    /**
     * Creates new form CompraHistorialCarrito
     */
    public CompraHistorialCarrito(Compras compra) {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.GRAY),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        setBackground(Color.WHITE);

        // Información básica
        add(new JLabel("Código de compra: " + compra.getCodigoCompra()));
        add(new JLabel("Correo usuario: " + compra.getCorreoUsuario()));
        add(new JLabel("Fecha de compra: " + compra.getFechaCompra()));
        add(new JLabel("Estado: " + (compra.isEstadoCompra() ? "Completada" : "En carrito")));

        // Contenido comprado
        add(new JLabel("Contenido comprado:"));
        for (Multimedia contenido : compra.getContenidoComprado()) {
            add(new JLabel(" - " + contenido.getTitulo() + " (" + contenido.getClass().getSimpleName() + ")"));
        }

        // Enlaces de descarga
        add(new JLabel("Enlaces de descarga:"));
        for (EnlaceDescarga enlace : compra.getListaEnlacesDescarga()) {
            String estado = enlace.isEstadoDescarga() ? "Descargado" : "No descargado";
            add(new JLabel(" • " + enlace.getEnlaceGenerado() + " [" + estado + "]"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
