/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import model.Album;
import model.Cancion;

/**
 *
 * @author PC
 */
public class PanelPanelSongs extends javax.swing.JPanel {

    /**
     * Creates new form PanelPanelSongs
     */
    public PanelPanelSongs(Album album) {
        initComponents();
        tituloLabel.setText(album.getTitulo());
        artistasLabel.setText(album.getArtistas());
        anioLabel.setText(Integer.toString(album.getAnio()));
        generosLabel.setText(album.getGeneros());
        precioLabel.setText(Float.toString(album.getPrecio()));
        selloLabel.setText(album.getSelloDiscografico());

        if (album.getUrlPortada() != null && !album.getUrlPortada().isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                try {
                    URL url = new URL(album.getUrlPortada());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                            imgPortada.getWidth() > 0 ? imgPortada.getWidth() : 100,
                            imgPortada.getHeight() > 0 ? imgPortada.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );

                    JLabel imgLabel = new JLabel(new ImageIcon(img));
                    imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    imgLabel.setVerticalAlignment(SwingConstants.CENTER);

                    imgPortada.setLayout(new BorderLayout());
                    imgPortada.add(imgLabel, BorderLayout.CENTER);
                    imgPortada.revalidate();
                    imgPortada.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        for (Cancion c : album.getCancionesAlbum()) {
            TarjetaCancion tarjetaCancion = new TarjetaCancion(c);
            panelShowData.add(tarjetaCancion);
        }

        panelShowData.revalidate();
        panelShowData.repaint();

        imgPortada.revalidate();
        imgPortada.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgPortada = new javax.swing.JPanel();
        panelScrollData = new javax.swing.JScrollPane();
        panelShowData = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        anioLabel = new javax.swing.JLabel();
        generosLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        artistasLabel = new javax.swing.JLabel();
        selloLabel = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(881, 493));

        jPanel1.setPreferredSize(new java.awt.Dimension(881, 493));

        javax.swing.GroupLayout imgPortadaLayout = new javax.swing.GroupLayout(imgPortada);
        imgPortada.setLayout(imgPortadaLayout);
        imgPortadaLayout.setHorizontalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        imgPortadaLayout.setVerticalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelShowDataLayout = new javax.swing.GroupLayout(panelShowData);
        panelShowData.setLayout(panelShowDataLayout);
        panelShowDataLayout.setHorizontalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        panelShowDataLayout.setVerticalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        panelScrollData.setViewportView(panelShowData);

        tituloLabel.setText("Titulos");

        anioLabel.setText("Anio");

        generosLabel.setText("Genero");

        precioLabel.setText("Precio");

        artistasLabel.setText("Artistas");

        selloLabel.setText("Sello");

        agregarBtn.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel)
                            .addComponent(anioLabel)
                            .addComponent(generosLabel)
                            .addComponent(artistasLabel)
                            .addComponent(selloLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioLabel)
                            .addComponent(agregarBtn))
                        .addGap(52, 52, 52)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precioLabel)
                            .addComponent(tituloLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(artistasLabel)
                            .addComponent(agregarBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generosLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JLabel anioLabel;
    private javax.swing.JLabel artistasLabel;
    private javax.swing.JLabel generosLabel;
    private javax.swing.JPanel imgPortada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane panelScrollData;
    private javax.swing.JPanel panelShowData;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel selloLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
