/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import model.Serie;

/**
 *
 * @author PC
 */
public class TarjetaSerie extends javax.swing.JPanel {

    /**
     * Creates new form TarjetaSerie
     */
    public TarjetaSerie(Serie serie) {
        initComponents();
        tituloLabel.setText(serie.getTitulo());
        sinopsisLabel.setText(serie.getSinopsis());
        anioLabel.setText(Integer.toString(serie.getAnio()));
        generosLabel.setText(serie.getGeneros());
        precioLabel.setText(Float.toString(serie.getPrecio()));
        formatoLabel.setText(serie.getFormato());
        temporadasLabel.setText(Integer.toString(serie.getTemporadas()));
        
        if (serie.getUrlPortada()!= null && !serie.getUrlPortada().isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                try {
                    URL url = new URL(serie.getUrlPortada());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                           imgPortada.getWidth() > 0 ?imgPortada.getWidth() : 100,
                           imgPortada.getHeight() > 0 ?imgPortada.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );

                    JLabel imgLabel = new JLabel(new ImageIcon(img));
                    imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    imgLabel.setVerticalAlignment(SwingConstants.CENTER);

                   imgPortada.setLayout(new BorderLayout());
                   imgPortada.add(imgLabel, BorderLayout.CENTER);
                   imgPortada.revalidate();
                   imgPortada.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        
        imgPortada.revalidate();
        imgPortada.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPortada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        precioLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        generosLabel = new javax.swing.JLabel();
        anioLabel = new javax.swing.JLabel();
        sinopsisLabel = new javax.swing.JLabel();
        formatoLabel = new javax.swing.JLabel();
        temporadasLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(219, 182, 235));

        javax.swing.GroupLayout imgPortadaLayout = new javax.swing.GroupLayout(imgPortada);
        imgPortada.setLayout(imgPortadaLayout);
        imgPortadaLayout.setHorizontalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        imgPortadaLayout.setVerticalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 58, 128));
        jLabel1.setText("Titulo: ");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 58, 128));
        jLabel2.setText("Genero(s):");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 58, 128));
        jLabel3.setText("Año de lanzamiento: ");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(105, 58, 128));
        jLabel4.setText("Formato:");

        jButton1.setBackground(new java.awt.Color(105, 58, 128));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(235, 220, 236));
        jButton1.setText("Agregar");

        precioLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        precioLabel.setForeground(new java.awt.Color(105, 58, 128));
        precioLabel.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 58, 128));
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(105, 58, 128));
        jLabel6.setText("Sinopsis: ");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 58, 128));
        jLabel7.setText("Temporadas: ");

        tituloLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(105, 58, 128));
        tituloLabel.setText("jLabel8");

        generosLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        generosLabel.setForeground(new java.awt.Color(105, 58, 128));
        generosLabel.setText("jLabel8");

        anioLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        anioLabel.setForeground(new java.awt.Color(105, 58, 128));
        anioLabel.setText("jLabel8");

        sinopsisLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        sinopsisLabel.setForeground(new java.awt.Color(105, 58, 128));
        sinopsisLabel.setText("jLabel8");
        sinopsisLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        formatoLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        formatoLabel.setForeground(new java.awt.Color(105, 58, 128));
        formatoLabel.setText("jLabel8");

        temporadasLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        temporadasLabel.setForeground(new java.awt.Color(105, 58, 128));
        temporadasLabel.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(36, 36, 36)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precioLabel)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(generosLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tituloLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(anioLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(formatoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(sinopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(temporadasLabel))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tituloLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generosLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(anioLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(formatoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temporadasLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(precioLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sinopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioLabel;
    private javax.swing.JLabel formatoLabel;
    private javax.swing.JLabel generosLabel;
    private javax.swing.JPanel imgPortada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel sinopsisLabel;
    private javax.swing.JLabel temporadasLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
