/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import Reproducir.Reproducir;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import DAO.CarritoDAO;
import model.Cancion;

/**
 *
 * @author cybergato
 */
public class TarjetaCancion extends javax.swing.JPanel {

    private Cancion cancion;
    private Reproducir rep;
    private boolean estaReproduciendo = false;

    public TarjetaCancion(Cancion cancion) {
        this.cancion = cancion;
        initComponents();
        nombreCancionLbl.setText(cancion.getTitulo());
        nombreArtistaLbl.setText(cancion.getArtistas());
        edicionLbl.setText(cancion.getEdicion());
        selloLbl.setText(cancion.getSello());
        generoLbl.setText(cancion.getGeneros());

        // Cargar imagen
        if (cancion.getUrlPortada() != null && !cancion.getUrlPortada().isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                try {
                    URL url = new URL(cancion.getUrlPortada());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                            imgIconPista.getWidth() > 0 ? imgIconPista.getWidth() : 100,
                            imgIconPista.getHeight() > 0 ? imgIconPista.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );

                    JLabel imgLabel = new JLabel(new ImageIcon(img));
                    imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    imgLabel.setVerticalAlignment(SwingConstants.CENTER);

                    imgIconPista.setLayout(new BorderLayout());
                    imgIconPista.add(imgLabel, BorderLayout.CENTER);
                    imgIconPista.revalidate();
                    imgIconPista.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        // Refrescar panel
        imgIconPista.revalidate();
        imgIconPista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPista = new javax.swing.JPanel();
        imgIconPista = new javax.swing.JPanel();
        nombreCancionLbl = new javax.swing.JLabel();
        tipoLbl = new javax.swing.JLabel();
        nombreArtistaLbl = new javax.swing.JLabel();
        selloLbl = new javax.swing.JLabel();
        edicionLbl = new javax.swing.JLabel();
        generoLbl = new javax.swing.JLabel();
        reproducirBtn = new javax.swing.JButton();
        agregarLbl = new javax.swing.JButton();

        panelPista.setBackground(new java.awt.Color(219, 182, 235));

        javax.swing.GroupLayout imgIconPistaLayout = new javax.swing.GroupLayout(imgIconPista);
        imgIconPista.setLayout(imgIconPistaLayout);
        imgIconPistaLayout.setHorizontalGroup(
            imgIconPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        imgIconPistaLayout.setVerticalGroup(
            imgIconPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        nombreCancionLbl.setBackground(new java.awt.Color(105, 58, 128));
        nombreCancionLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        nombreCancionLbl.setForeground(new java.awt.Color(105, 58, 128));
        nombreCancionLbl.setText("Nombre de la cancion");

        tipoLbl.setBackground(new java.awt.Color(105, 58, 128));
        tipoLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        tipoLbl.setForeground(new java.awt.Color(105, 58, 128));
        tipoLbl.setText("Tipo");

        nombreArtistaLbl.setBackground(new java.awt.Color(105, 58, 128));
        nombreArtistaLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        nombreArtistaLbl.setForeground(new java.awt.Color(105, 58, 128));
        nombreArtistaLbl.setText("Nombre del artista");

        selloLbl.setBackground(new java.awt.Color(105, 58, 128));
        selloLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        selloLbl.setForeground(new java.awt.Color(105, 58, 128));
        selloLbl.setText("Sello discografico");

        edicionLbl.setBackground(new java.awt.Color(105, 58, 128));
        edicionLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        edicionLbl.setForeground(new java.awt.Color(105, 58, 128));
        edicionLbl.setText("Edicion: ");

        generoLbl.setBackground(new java.awt.Color(105, 58, 128));
        generoLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        generoLbl.setForeground(new java.awt.Color(105, 58, 128));
        generoLbl.setText("Genero:");

        reproducirBtn.setBackground(new java.awt.Color(238, 229, 242));
        reproducirBtn.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        reproducirBtn.setForeground(new java.awt.Color(105, 58, 128));
        reproducirBtn.setText("Reproducir");
        reproducirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirBtnActionPerformed(evt);
            }
        });

        agregarLbl.setBackground(new java.awt.Color(238, 229, 242));
        agregarLbl.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        agregarLbl.setForeground(new java.awt.Color(105, 58, 128));
        agregarLbl.setText("Agregar");
        agregarLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPistaLayout = new javax.swing.GroupLayout(panelPista);
        panelPista.setLayout(panelPistaLayout);
        panelPistaLayout.setHorizontalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgIconPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPistaLayout.createSequentialGroup()
                        .addComponent(nombreCancionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edicionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(panelPistaLayout.createSequentialGroup()
                        .addComponent(nombreArtistaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reproducirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        panelPistaLayout.setVerticalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgIconPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPistaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCancionLbl)
                            .addComponent(selloLbl)
                            .addComponent(edicionLbl)
                            .addComponent(reproducirBtn))
                        .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPistaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreArtistaLbl)
                                    .addComponent(generoLbl)
                                    .addComponent(tipoLbl)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPistaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarLbl)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAlCarrito() {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Canción agregada al carrito!");
        //
        CarritoDAO.agregarMultimedia(cancion);
    }

    private void reproducirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirBtnActionPerformed
        if (rep == null || !estaReproduciendo) {
            rep = new Reproducir();
            rep.Reproducir(this.cancion.getUrlCancion());
            estaReproduciendo = true;
            reproducirBtn.setText("Pausa");
        } else {
            rep.Pausar();  // En este caso sería más un 'parar'
            estaReproduciendo = false;
            reproducirBtn.setText("Reproducir");
        }
    }//GEN-LAST:event_reproducirBtnActionPerformed

    private void agregarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLblActionPerformed
        agregarAlCarrito();
    }//GEN-LAST:event_agregarLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarLbl;
    private javax.swing.JLabel edicionLbl;
    private javax.swing.JLabel generoLbl;
    private javax.swing.JPanel imgIconPista;
    private javax.swing.JLabel nombreArtistaLbl;
    private javax.swing.JLabel nombreCancionLbl;
    private javax.swing.JPanel panelPista;
    private javax.swing.JButton reproducirBtn;
    private javax.swing.JLabel selloLbl;
    private javax.swing.JLabel tipoLbl;
    // End of variables declaration//GEN-END:variables
}
