/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import Reproducir.Reproducir;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import model.Cancion;

/**
 *
 * @author PC
 */
public class TarjetaAlbumCancion extends javax.swing.JPanel {

    /**
     * Creates new form TarjetaAlbumCancion
     */
    private Cancion cancion;
    private Reproducir rep;
    private boolean estaReproduciendo = false;

    public TarjetaAlbumCancion(Cancion cancion) {

        initComponents();
        this.cancion = cancion;
        initComponents();
        nombreCancionLbl.setText(cancion.getTitulo());
        duracionLbl.setText(Integer.toString(cancion.getDuracion()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPista = new javax.swing.JPanel();
        nombreCancionLbl = new javax.swing.JLabel();
        duracionLbl = new javax.swing.JLabel();
        reproducirBtn = new javax.swing.JButton();
        agregarLbl = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(881, 53));

        nombreCancionLbl.setText("Nombre de la cancion");

        duracionLbl.setText("Duracion");

        reproducirBtn.setText("Play");
        reproducirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirBtnActionPerformed(evt);
            }
        });

        agregarLbl.setText("Add");
        agregarLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPistaLayout = new javax.swing.GroupLayout(panelPista);
        panelPista.setLayout(panelPistaLayout);
        panelPistaLayout.setHorizontalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reproducirBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCancionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracionLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPistaLayout.setVerticalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reproducirBtn)
                    .addComponent(agregarLbl)
                    .addComponent(duracionLbl)
                    .addComponent(nombreCancionLbl))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarLblActionPerformed

    private void reproducirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirBtnActionPerformed
        if (rep == null || !estaReproduciendo) {
            rep = new Reproducir();
            rep.Reproducir(this.cancion.getUrlCancion());
            estaReproduciendo = true;
            reproducirBtn.setText("Pausa");
        } else {
            rep.Pausar();  // En este caso sería más un 'parar'
            estaReproduciendo = false;
            reproducirBtn.setText("Play");
        }
    }//GEN-LAST:event_reproducirBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarLbl;
    private javax.swing.JLabel duracionLbl;
    private javax.swing.JLabel nombreCancionLbl;
    private javax.swing.JPanel panelPista;
    private javax.swing.JButton reproducirBtn;
    // End of variables declaration//GEN-END:variables
}
