/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import model.Multimedia;

import javax.swing.*;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author cybergato
 */
public class TarjetaCarrito extends javax.swing.JPanel {

    private Multimedia multimedia;

    public TarjetaCarrito(Multimedia multimedia) {
        this.multimedia = multimedia;
        initComponents();
        nombreMultimediaLbl.setText(multimedia.getTitulo());
        generoLbl.setText(multimedia.getGeneros());
        anioLbl.setText(String.valueOf(multimedia.getAnio()));
        precioLbl.setText("$" + multimedia.getPrecio());

        // Cargar imagen
        if (multimedia.getUrlPortada()!= null && !multimedia.getUrlPortada().isEmpty()) {
            SwingUtilities.invokeLater(() -> {
                try {
                    URL url = new URL(multimedia.getUrlPortada());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                            imgIconPista.getWidth() > 0 ? imgIconPista.getWidth() : 100,
                            imgIconPista.getHeight() > 0 ? imgIconPista.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );

                    JLabel imgLabel = new JLabel(new ImageIcon(img));
                    imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                    imgLabel.setVerticalAlignment(SwingConstants.CENTER);

                    imgIconPista.setLayout(new BorderLayout());
                    imgIconPista.add(imgLabel, BorderLayout.CENTER);
                    imgIconPista.revalidate();
                    imgIconPista.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        // Refrescar panel
        imgIconPista.revalidate();
        imgIconPista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPista = new javax.swing.JPanel();
        imgIconPista = new javax.swing.JPanel();
        nombreMultimediaLbl = new javax.swing.JLabel();
        tipoLbl = new javax.swing.JLabel();
        nombreArtistaLbl = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        anioLbl = new javax.swing.JLabel();
        generoLbl = new javax.swing.JLabel();

        javax.swing.GroupLayout imgIconPistaLayout = new javax.swing.GroupLayout(imgIconPista);
        imgIconPista.setLayout(imgIconPistaLayout);
        imgIconPistaLayout.setHorizontalGroup(
            imgIconPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        imgIconPistaLayout.setVerticalGroup(
            imgIconPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        nombreMultimediaLbl.setText("Nombre de la cancion");

        tipoLbl.setText("Tipo");

        nombreArtistaLbl.setText("Nombre del artista");

        precioLbl.setText("Sello discografico");

        anioLbl.setText("Edicion: ");

        generoLbl.setText("Genero:");

        javax.swing.GroupLayout panelPistaLayout = new javax.swing.GroupLayout(panelPista);
        panelPista.setLayout(panelPistaLayout);
        panelPistaLayout.setHorizontalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgIconPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreMultimediaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreArtistaLbl))
                .addGap(58, 58, 58)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioLbl))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelPistaLayout.setVerticalGroup(
            panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgIconPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPistaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreMultimediaLbl)
                            .addComponent(precioLbl)
                            .addComponent(anioLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreArtistaLbl)
                            .addComponent(generoLbl)
                            .addComponent(tipoLbl))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
                                          


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioLbl;
    private javax.swing.JLabel generoLbl;
    private javax.swing.JPanel imgIconPista;
    private javax.swing.JLabel nombreArtistaLbl;
    private javax.swing.JLabel nombreMultimediaLbl;
    private javax.swing.JPanel panelPista;
    private javax.swing.JLabel precioLbl;
    private javax.swing.JLabel tipoLbl;
    // End of variables declaration//GEN-END:variables
}
