/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.net.URL;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import DAO.CancionDAO;
import interfaces.Carrito;
import model.Album;
import model.Cancion;

/**
 *
 * @author cybergato
 */
public class TarjetaAlbum extends javax.swing.JPanel {

    /**
     * Creates new form TarjetaAlbum
     */
    
    private Album album;
    private JPanel panelShowData;
    
    public TarjetaAlbum(Album album, JPanel panelShowData) {
        
        this.album = album;
        this.panelShowData = panelShowData;
        
        initComponents();
        nombreAlbumLbl.setText(album.getTitulo());
        nombreArtistaLbl.setText(album.getArtistas());
        anoLbl.setText(Integer.toString(album.getAnio()));
        
        // Cargar imagen
        if (album.getUrlPortada() != null && !album.getUrlPortada().isEmpty()) {
            imagenIconContainer.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    imagenIconContainer.removeComponentListener(this); // Para que no se llame más de una vez
                    cargarImagen(album.getUrlPortada());
                }
            });
        }

        // Refrescar panel
        imagenIconContainer.revalidate();
        imagenIconContainer.repaint();
    }

    private void cargarImagen(String urlStr) {
        try {
            URL url = new URL(urlStr);
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(
                    imagenIconContainer.getWidth(),
                    imagenIconContainer.getHeight(),
                    Image.SCALE_SMOOTH
            );

            JLabel imgLabel = new JLabel(new ImageIcon(img));
            imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
            imgLabel.setVerticalAlignment(SwingConstants.CENTER);

            imagenIconContainer.setLayout(new BorderLayout());
            imagenIconContainer.removeAll(); // Limpia imágenes anteriores
            imagenIconContainer.add(imgLabel, BorderLayout.CENTER);
            imagenIconContainer.revalidate();
            imagenIconContainer.repaint();
        } catch (Exception e) {
            System.out.println("Error cargando imagen: " + urlStr);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlbum = new javax.swing.JPanel();
        imagenIconContainer = new javax.swing.JPanel();
        nombreAlbumLbl = new javax.swing.JLabel();
        nombreArtistaLbl = new javax.swing.JLabel();
        anoLbl = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        verCancionesBtn = new javax.swing.JButton();

        javax.swing.GroupLayout imagenIconContainerLayout = new javax.swing.GroupLayout(imagenIconContainer);
        imagenIconContainer.setLayout(imagenIconContainerLayout);
        imagenIconContainerLayout.setHorizontalGroup(
            imagenIconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        imagenIconContainerLayout.setVerticalGroup(
            imagenIconContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        nombreAlbumLbl.setText("Nombre del album");

        nombreArtistaLbl.setText("Nombre del artista");

        anoLbl.setText("Año de creacion");

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        verCancionesBtn.setText("Ver canciones");
        verCancionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCancionesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlbumLayout = new javax.swing.GroupLayout(panelAlbum);
        panelAlbum.setLayout(panelAlbumLayout);
        panelAlbumLayout.setHorizontalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarBtn)
                    .addComponent(imagenIconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreAlbumLbl)
                    .addComponent(nombreArtistaLbl)
                    .addComponent(verCancionesBtn)
                    .addComponent(anoLbl))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelAlbumLayout.setVerticalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagenIconContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAlbumLayout.createSequentialGroup()
                        .addComponent(nombreAlbumLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreArtistaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anoLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBtn)
                    .addComponent(verCancionesBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verCancionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCancionesBtnActionPerformed
        if (panelShowData == null) {
            System.err.println("panelShowData es null");
            return;
        }
        CancionDAO cancionDAO = new CancionDAO();
        List<Cancion> canciones = cancionDAO.getCancionesPorAlbum(album.getIdAlbum());
        album.setCancionesAlbum(canciones);
        PanelPanelSongs panelCanciones = new PanelPanelSongs(album);
        panelShowData.removeAll();
        panelShowData.setLayout(new BorderLayout()); // o el layout que uses
        panelShowData.add(new PanelPanelSongs(album), BorderLayout.CENTER);
        panelShowData.revalidate();
        panelShowData.repaint();
        
    }//GEN-LAST:event_verCancionesBtnActionPerformed

    private void agregarAlCarrito() {

        Carrito.agregarAlbum(album);
        javax.swing.JOptionPane.showMessageDialog(this, "¡Album agregado al carrito!");
    }

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        agregarAlCarrito();
    }//GEN-LAST:event_agregarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JLabel anoLbl;
    private javax.swing.JPanel imagenIconContainer;
    private javax.swing.JLabel nombreAlbumLbl;
    private javax.swing.JLabel nombreArtistaLbl;
    private javax.swing.JPanel panelAlbum;
    private javax.swing.JButton verCancionesBtn;
    // End of variables declaration//GEN-END:variables
}
