/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.*;

import DAO.CarritoDAO;
import model.Pelicula;

/**
 *
 * @author PC
 */
public class TarjetaPelicula extends javax.swing.JPanel {

    private Pelicula pelicula;
    public TarjetaPelicula(Pelicula pelicula) {
        initComponents();
        this.pelicula = pelicula;
        tituloLabel.setText(pelicula.getTitulo());
        sinopsisLabel.setText(pelicula.getSinopsis());
        actoresLabel.setText(pelicula.getActores());
        anioLabel.setText(Integer.toString(pelicula.getAnio()));
        duracionLabel.setText(pelicula.getDuracion());
        generosLabel.setText(pelicula.getGeneros());

        if (pelicula.getUrlPortada() != null && !pelicula.getUrlPortada().isEmpty()) {
            new SwingWorker<ImageIcon, Void>() {
                @Override
                protected ImageIcon doInBackground() throws Exception {
                    URL url = new URL(pelicula.getUrlPortada());
                    ImageIcon icon = new ImageIcon(url);
                    Image img = icon.getImage().getScaledInstance(
                            imgPortada.getWidth() > 0 ? imgPortada.getWidth() : 100,
                            imgPortada.getHeight() > 0 ? imgPortada.getHeight() : 100,
                            Image.SCALE_SMOOTH
                    );
                    return new ImageIcon(img);
                }

                @Override
                protected void done() {
                    try {
                        ImageIcon iconoFinal = get();
                        JLabel imgLabel = new JLabel(iconoFinal);
                        imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
                        imgLabel.setVerticalAlignment(SwingConstants.CENTER);
                        imgPortada.setLayout(new BorderLayout());
                        imgPortada.add(imgLabel, BorderLayout.CENTER);
                        imgPortada.revalidate();
                        imgPortada.repaint();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }.execute();
        }

        imgPortada.revalidate();
        imgPortada.repaint();


    }

    private void agregarAlCarrito() {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Pelicula agregada al carrito!");
        CarritoDAO.agregarMultimedia(pelicula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgPortada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sinopsisLabel = new javax.swing.JLabel();
        anioLabel = new javax.swing.JLabel();
        generosLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        actoresLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        duracionLabel = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(219, 182, 235));

        javax.swing.GroupLayout imgPortadaLayout = new javax.swing.GroupLayout(imgPortada);
        imgPortada.setLayout(imgPortadaLayout);
        imgPortadaLayout.setHorizontalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        imgPortadaLayout.setVerticalGroup(
            imgPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 58, 128));
        jLabel1.setText("Titulo: ");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 58, 128));
        jLabel2.setText("Genero(s):");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 58, 128));
        jLabel3.setText("Año de lanzamiento: ");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(105, 58, 128));
        jLabel4.setText("Sinopsis: ");

        sinopsisLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        sinopsisLabel.setForeground(new java.awt.Color(105, 58, 128));
        sinopsisLabel.setText("jLabel5");
        sinopsisLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        anioLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        anioLabel.setForeground(new java.awt.Color(105, 58, 128));
        anioLabel.setText("anioLabel");

        generosLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        generosLabel.setForeground(new java.awt.Color(105, 58, 128));
        generosLabel.setText("generosLabel");

        tituloLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(105, 58, 128));
        tituloLabel.setText("titulo");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 58, 128));
        jLabel5.setText("Actore(s):");

        actoresLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        actoresLabel.setForeground(new java.awt.Color(105, 58, 128));
        actoresLabel.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(105, 58, 128));
        jLabel6.setText("Duracion: ");

        duracionLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        duracionLabel.setForeground(new java.awt.Color(105, 58, 128));
        duracionLabel.setText("jLabel7");

        agregarBtn.setBackground(new java.awt.Color(105, 58, 128));
        agregarBtn.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        agregarBtn.setForeground(new java.awt.Color(235, 220, 236));
        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 58, 128));
        jLabel7.setText("Precio:");

        precioLabel.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        precioLabel.setForeground(new java.awt.Color(105, 58, 128));
        precioLabel.setText("precio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(agregarBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(precioLabel)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duracionLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(anioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(generosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(actoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarBtn)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precioLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tituloLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(generosLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(anioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(actoresLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(duracionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sinopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        agregarAlCarrito();
    }//GEN-LAST:event_agregarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actoresLabel;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JLabel anioLabel;
    private javax.swing.JLabel duracionLabel;
    private javax.swing.JLabel generosLabel;
    private javax.swing.JPanel imgPortada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel sinopsisLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
