/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import DAO.AlbumDAO;
import DAO.CancionDAO;
import DAO.ComprasDAO;
import DAO.PeliculasDAO;
import DAO.SeriesDAO;
import interfaces.gui.*;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import model.Album;
import model.Cancion;
import model.Compras;
import model.Pelicula;
import model.Serie;

/**
 *
 * @author cybergato
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    AlbumDAO albumDAO = new AlbumDAO();
    CancionDAO pistaDAO = new CancionDAO();
    PeliculasDAO peliculaDAO = new PeliculasDAO();
    SeriesDAO seriesDAO = new SeriesDAO();

    List<Album> albumsList = albumDAO.getAlbum();
    List<Pelicula> peliculasList = peliculaDAO.getPeliculas();
    List<Serie> seriesList = seriesDAO.getSeries();

    public MainApp() {

        initComponents();
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        for (Album a : albumsList) {
            TarjetaAlbum tarjetaAlbum = new TarjetaAlbum(a, panelShowData); // ¡Este es el importante!
            panelShowData.add(tarjetaAlbum);
        }

        panelShowData.revalidate();
        panelShowData.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGroundPanel = new javax.swing.JPanel();
        sideMenuPanel = new javax.swing.JPanel();
        titleApp = new javax.swing.JLabel();
        btnCanciones = new javax.swing.JButton();
        btnAlbumes = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnSeries = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        historialBtn = new javax.swing.JButton();
        carritoBtn = new javax.swing.JButton();
        mainContainerPanel = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        panelScrollData = new javax.swing.JScrollPane();
        panelShowData = new javax.swing.JPanel();
        comprarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideMenuPanel.setBackground(new java.awt.Color(96, 39, 125));
        sideMenuPanel.setForeground(new java.awt.Color(96, 39, 125));

        titleApp.setForeground(new java.awt.Color(238, 229, 242));
        titleApp.setText("Hobito");

        btnCanciones.setText("Canciones");
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        btnAlbumes.setText("Albumes");
        btnAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesActionPerformed(evt);
            }
        });

        btnPeliculas.setText("Peliculas");
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });

        btnSeries.setText("Series");
        btnSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeriesActionPerformed(evt);
            }
        });

        jLabel1.setText("Compras");

        historialBtn.setText("Historial");
        historialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBtnActionPerformed(evt);
            }
        });

        carritoBtn.setText("Carrito");
        carritoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carritoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuPanelLayout = new javax.swing.GroupLayout(sideMenuPanel);
        sideMenuPanel.setLayout(sideMenuPanelLayout);
        sideMenuPanelLayout.setHorizontalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carritoBtn)
                    .addComponent(historialBtn)
                    .addComponent(jLabel1)
                    .addComponent(btnSeries)
                    .addComponent(btnPeliculas)
                    .addComponent(btnAlbumes)
                    .addComponent(btnCanciones)
                    .addComponent(titleApp))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        sideMenuPanelLayout.setVerticalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleApp)
                .addGap(32, 32, 32)
                .addComponent(btnCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPeliculas)
                .addGap(18, 18, 18)
                .addComponent(btnSeries)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carritoBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainContainerPanel.setForeground(new java.awt.Color(238, 229, 242));

        mainTitleLabel.setText("Pagina principal");

        javax.swing.GroupLayout panelShowDataLayout = new javax.swing.GroupLayout(panelShowData);
        panelShowData.setLayout(panelShowDataLayout);
        panelShowDataLayout.setHorizontalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        panelShowDataLayout.setVerticalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        panelScrollData.setViewportView(panelShowData);

        comprarBtn.setText("Comprar");
        comprarBtn.setDoubleBuffered(true);
        comprarBtn.setVisible(false);
        comprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainContainerPanelLayout = new javax.swing.GroupLayout(mainContainerPanel);
        mainContainerPanel.setLayout(mainContainerPanelLayout);
        mainContainerPanelLayout.setHorizontalGroup(
            mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comprarBtn)
                    .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTitleLabel))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        mainContainerPanelLayout.setVerticalGroup(
            mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(mainTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comprarBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backGroundPanelLayout = new javax.swing.GroupLayout(backGroundPanel);
        backGroundPanel.setLayout(backGroundPanelLayout);
        backGroundPanelLayout.setHorizontalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPanelLayout.createSequentialGroup()
                .addComponent(sideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backGroundPanelLayout.setVerticalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {
        panelShowData.removeAll();

        CancionDAO pistaDAO = new CancionDAO();
        List<Cancion> cancionesList = pistaDAO.getPistas1();

        for (Cancion p : cancionesList) {
            TarjetaCancion tarjeta = new TarjetaCancion(p);
            panelShowData.add(tarjeta);
        }

        panelShowData.revalidate();
        panelShowData.repaint();
        comprarBtn.setVisible(false);

    }                                            

    private void btnAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesActionPerformed
        panelShowData.setPreferredSize(new Dimension(760, 500));
        panelShowData.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 16));

        panelShowData.removeAll();
        panelShowData.revalidate();
        panelShowData.repaint();

        for (Album a : albumsList) {
            TarjetaAlbum tarjetaAlbum = new TarjetaAlbum(a, panelShowData); // ¡Este es el importante!
            panelShowData.add(tarjetaAlbum);
        }
        comprarBtn.setVisible(false);
    }//GEN-LAST:event_btnAlbumesActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();
        panelShowData.revalidate();
        panelShowData.repaint();

        for (Pelicula p : peliculasList) {
            TarjetaPelicula tarjetaPeliculaGUI = new TarjetaPelicula(p);
            panelShowData.add(tarjetaPeliculaGUI);
        }
        comprarBtn.setVisible(false);

    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeriesActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();
        panelShowData.revalidate();
        panelShowData.repaint();

        for (Serie s : seriesList) {
            TarjetaSerie tarjetaSerie = new TarjetaSerie(s);
            panelShowData.add(tarjetaSerie);
        }
        comprarBtn.setVisible(false);

    }//GEN-LAST:event_btnSeriesActionPerformed

    private void historialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBtnActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();

        ComprasDAO comprasDAO = new ComprasDAO();
        List<Compras> lista = comprasDAO.getCompras(); // o getCarrito()

        for (Compras c : lista) {
            CompraHistorialCarrito componente = new CompraHistorialCarrito(c);
            panelShowData.add(componente);
        }

        comprarBtn.setVisible(false);
        panelShowData.revalidate();
        panelShowData.repaint();
    }//GEN-LAST:event_historialBtnActionPerformed

    private void carritoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carritoBtnActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();

        for (Cancion c : Carrito.getCanciones()) {
            TarjetaCancionCompra tarjeta = new TarjetaCancionCompra(c);
            panelShowData.add(tarjeta);
        }

        comprarBtn.setVisible(true);
        panelShowData.revalidate();
        panelShowData.repaint();
    }//GEN-LAST:event_carritoBtnActionPerformed

    private void comprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGroundPanel;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSeries;
    private javax.swing.JButton carritoBtn;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JButton historialBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainContainerPanel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JScrollPane panelScrollData;
    private javax.swing.JPanel panelShowData;
    private javax.swing.JPanel sideMenuPanel;
    private javax.swing.JLabel titleApp;
    // End of variables declaration//GEN-END:variables
}
