/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import DAO.*;
import SAS.generarCompraTicket;
import interfaces.gui.*;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;

import model.*;
import org.json.JSONObject;

/**
 *
 * @author cybergato
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    AlbumDAO albumDAO = new AlbumDAO();
    SeriesDAO seriesDAO = new SeriesDAO();
    Usuario u = SesionUsuario.getUsuario();

    List<Album> albumsList = albumDAO.getAlbum1();
    List<Serie> seriesList = seriesDAO.getSeries();

    public MainApp() {

        initComponents();
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        for (Album a : albumsList) {
            TarjetaAlbum tarjetaAlbum = new TarjetaAlbum(a, panelShowData); // ¡Este es el importante!
            panelShowData.add(tarjetaAlbum);
        }

        panelShowData.revalidate();
        panelShowData.repaint();
    }

    public static void setFixedSize(java.awt.Component component, int width) {
        java.awt.Dimension d = new java.awt.Dimension(width, component.getHeight());
        component.setPreferredSize(d);
        component.setMinimumSize(d);
        component.setMaximumSize(d);
        component.setSize(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGroundPanel = new javax.swing.JPanel();
        mainContainerPanel = new javax.swing.JPanel();
        panelScrollData = new javax.swing.JScrollPane();
        panelShowData = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titleApp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carritoBtn = new javax.swing.JButton();
        comprarBtn = new javax.swing.JButton();
        historialBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAlbumes = new javax.swing.JButton();
        btnCanciones = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnSeries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContainerPanel.setBackground(new java.awt.Color(219, 182, 235));
        mainContainerPanel.setForeground(new java.awt.Color(238, 229, 242));

        panelShowData.setBackground(new java.awt.Color(235, 220, 236));

        javax.swing.GroupLayout panelShowDataLayout = new javax.swing.GroupLayout(panelShowData);
        panelShowData.setLayout(panelShowDataLayout);
        panelShowDataLayout.setHorizontalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        panelShowDataLayout.setVerticalGroup(
            panelShowDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        panelScrollData.setViewportView(panelShowData);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setForeground(new java.awt.Color(238, 229, 242));

        titleApp.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 55)); // NOI18N
        titleApp.setForeground(new java.awt.Color(153, 0, 153));
        titleApp.setText("Hobito");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hobitomini.png"))); // NOI18N

        carritoBtn.setBackground(new java.awt.Color(204, 153, 255));
        carritoBtn.setForeground(new java.awt.Color(204, 153, 255));
        carritoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart_icon-icons.com_64848 (1).png"))); // NOI18N
        carritoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carritoBtnActionPerformed(evt);
            }
        });

        comprarBtn.setBackground(new java.awt.Color(204, 153, 255));
        comprarBtn.setForeground(new java.awt.Color(204, 153, 255));
        comprarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartphone_credit_card_buy_payment_icon_143289.png"))); // NOI18N
        comprarBtn.setDoubleBuffered(true);
        comprarBtn.setOpaque(true);
        comprarBtn.setVisible(false);
        comprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBtnActionPerformed(evt);
            }
        });

        historialBtn.setBackground(new java.awt.Color(204, 153, 255));
        historialBtn.setForeground(new java.awt.Color(204, 153, 255));
        historialBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock_counter_clockwise_icon_173246 (1).png"))); // NOI18N
        historialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleApp)
                .addGap(199, 199, 199)
                .addComponent(historialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carritoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comprarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(historialBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carritoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleApp))
                .addGap(82, 82, 82))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        btnAlbumes.setBackground(new java.awt.Color(105, 58, 128));
        btnAlbumes.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnAlbumes.setForeground(new java.awt.Color(238, 229, 242));
        btnAlbumes.setText("Albumes");
        btnAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesActionPerformed(evt);
            }
        });

        btnCanciones.setBackground(new java.awt.Color(105, 58, 128));
        btnCanciones.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnCanciones.setForeground(new java.awt.Color(238, 229, 242));
        btnCanciones.setText("Canciones");
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        btnPeliculas.setBackground(new java.awt.Color(105, 58, 128));
        btnPeliculas.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnPeliculas.setForeground(new java.awt.Color(238, 229, 242));
        btnPeliculas.setText("Peliculas");
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });

        btnSeries.setBackground(new java.awt.Color(105, 58, 128));
        btnSeries.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btnSeries.setForeground(new java.awt.Color(238, 229, 242));
        btnSeries.setText("Series");
        btnSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainContainerPanelLayout = new javax.swing.GroupLayout(mainContainerPanel);
        mainContainerPanel.setLayout(mainContainerPanelLayout);
        mainContainerPanelLayout.setHorizontalGroup(
            mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainContainerPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainContainerPanelLayout.createSequentialGroup()
                        .addComponent(btnCanciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlbumes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeries)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        mainContainerPanelLayout.setVerticalGroup(
            mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrollData, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backGroundPanelLayout = new javax.swing.GroupLayout(backGroundPanel);
        backGroundPanel.setLayout(backGroundPanelLayout);
        backGroundPanelLayout.setHorizontalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backGroundPanelLayout.setVerticalGroup(
            backGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {
        panelShowData.removeAll();

        CancionDAO pistaDAO = new CancionDAO();
        List<Cancion> cancionesList = pistaDAO.getPistas1();

        for (Cancion p : cancionesList) {
            TarjetaCancion tarjeta = new TarjetaCancion(p);
            panelShowData.add(tarjeta);
        }

        panelShowData.revalidate();
        panelShowData.repaint();
        comprarBtn.setVisible(false);
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras

    }

    private void btnAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesActionPerformed
        panelShowData.removeAll();

        AlbumDAO albumDAO = new AlbumDAO();
        List<Album> albumsList = albumDAO.getAlbum1();

        for (Album a : albumsList) {
            TarjetaAlbum tarjetaAlbum = new TarjetaAlbum(a, panelShowData); // ¡Este es el importante!
            panelShowData.add(tarjetaAlbum);
        }

        panelShowData.revalidate();
        panelShowData.repaint();
        comprarBtn.setVisible(false);
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras

    }//GEN-LAST:event_btnAlbumesActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        PeliculasDAO peliculaDAO = new PeliculasDAO();
        List<Pelicula> peliculasList = peliculaDAO.getPeliculas1();
        panelShowData.removeAll();
        panelShowData.revalidate();
        panelShowData.repaint();

        for (Pelicula p : peliculasList) {
            TarjetaPelicula tarjetaPeliculaGUI = new TarjetaPelicula(p);
            panelShowData.add(tarjetaPeliculaGUI);
        }
        comprarBtn.setVisible(false);
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras


    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeriesActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();
        panelShowData.revalidate();
        panelShowData.repaint();

        for (Serie s : seriesList) {
            TarjetaSerie tarjetaSerie = new TarjetaSerie(s);
            panelShowData.add(tarjetaSerie);
        }
        comprarBtn.setVisible(false);
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras


    }//GEN-LAST:event_btnSeriesActionPerformed

    private void historialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBtnActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();

        ComprasDAO comprasDAO = new ComprasDAO();
        List<Compras> lista = comprasDAO.getCompras(u.getCorreo()); // o getCarrito()

        for (Compras c : lista) {
            CompraHistorialCarrito componente = new CompraHistorialCarrito(c);
            panelShowData.add(componente);
        }

        comprarBtn.setVisible(false);
        panelShowData.revalidate();
        panelShowData.repaint();
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras

    }//GEN-LAST:event_historialBtnActionPerformed

    private void carritoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carritoBtnActionPerformed
        panelShowData.setLayout(new BoxLayout(panelShowData, BoxLayout.Y_AXIS));
        panelShowData.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        panelShowData.removeAll();

        for (Multimedia c : CarritoDAO.getListaMultimedia()) {
            if (c instanceof Cancion) {
                TarjetaCarrito tarjeta = new TarjetaCarrito((Cancion) c);
                panelShowData.add(tarjeta);
            } else if (c instanceof Album) {
                TarjetaAlbum tarjeta = new TarjetaAlbum((Album) c, null);
                panelShowData.add(tarjeta);
            }else if(c instanceof Pelicula){
                TarjetaCarrito tarjeta = new TarjetaCarrito((Pelicula) c);
                panelShowData.add(tarjeta);// Puedes agregar más condiciones para otros tipos
            }else if(c instanceof Serie){
                TarjetaCarrito tarjeta = new TarjetaCarrito((Serie) c);
                panelShowData.add(tarjeta);
            }
        }

        comprarBtn.setVisible(true);
        panelShowData.revalidate();
        panelShowData.repaint();
        //setFixedSize(panelShowData, 881);
        setFixedSize(panelScrollData, 881); // O el tamaño que quieras

    }//GEN-LAST:event_carritoBtnActionPerformed

    private void comprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBtnActionPerformed
        JSONObject compra = generarCompraTicket.generarCompra(u.getCorreo(), CarritoDAO.getListaMultimedia());
        generarCompraTicket.guardarCompra(compra, u.getCorreo());
        CarritoDAO.getListaMultimedia().clear();
        javax.swing.JOptionPane.showMessageDialog(this, "¡Gracias por tu compra!");
    }//GEN-LAST:event_comprarBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGroundPanel;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSeries;
    private javax.swing.JButton carritoBtn;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JButton historialBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainContainerPanel;
    private javax.swing.JScrollPane panelScrollData;
    private javax.swing.JPanel panelShowData;
    private javax.swing.JLabel titleApp;
    // End of variables declaration//GEN-END:variables
}